"""audit_events

Revision ID: 8ce88e711b7d
Revises: c1c056366c7e
Create Date: 2026-07-11 15:12:58.494277

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ce88e711b7d'
down_revision: str | Sequence[str] | None = 'c1c056366c7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('capability_id', sa.Uuid(), nullable=True),
    sa.Column('connector_mode', sa.String(length=50), nullable=True),
    sa.Column('policy_decisions', sa.JSON(), nullable=True),
    sa.Column('risk_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('external_result_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
